### ISSUE TITLE
blocknum /timestamp crash occasionally

### ISSUE THREAD

**Issue by ShorelineCrypto** [ShorelineCrypto/cheetah_cpuminer#2]
Reported initially by member SAY (DISCORD) in window 7 running cheetah v1.1.0 

The similar crash also happened to my Linux for v1.1.0.  The crash is happening occasionally, not common events. 

NENG CPU Mining Started
block 175513: 1546674585 2019-01-05 07:49:50.784513 GMT
NENG CPU Mining Stopped
Traceback (most recent call last):
  File "main.py", line 141, in <module>
    main(args)
  File "main.py", line 116, in main
    blocknum = cheetah.run_cheetah(blocknum,config['rpcuser'], config['rpcpassword'], config['rpcport'], args.cpu)
  File "/home/hlu/cheetah_cpuminer/cpuminer/cheetah.py", line 18, in run_cheetah
    print "Block Time is ahead of current time, miner cheating or wrong timestamp {} {} GMT".format((bestblock['time'], datetime.utcnow()))
IndexError: tuple index out of range

**Comment by ShorelineCrypto** [comment]
The issue is fixed in new commit: https://github.com/ShorelineCrypto/cheetah_cpuminer/commit/7b829e6680a10701b25019cef86a37534dfac6a7
